Fix R example code
Currently line 53 "ETLSyntheaBuilder::LoadEventTables(cd,"synthea","synthea")" generates the following error:

Error: 'LoadEventTables' is not an exported object from 'namespace:ETLSyntheaBuilder'

Changed to "ETLSyntheaBuilder::LoadCDMTables(cd,"cdm_synthea10","native")"